version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_gateway
    environment:
      - POSTGRES_USER=gateway_user
      - POSTGRES_PASSWORD=gateway_pass
      - POSTGRES_DB=payment_gateway
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_gateway
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  dashboard:
    image: nginx:alpine
    container_name: dashboard_ui
    volumes:
      - ./frontend/dashboard:/usr/share/nginx/html
    ports:
      - "3000:80"

  checkout:
    image: nginx:alpine
    container_name: checkout_ui
    volumes:
      - ./frontend/checkout:/usr/share/nginx/html
      - ./checkout-widget/dist/checkout.js:/usr/share/nginx/html/checkout.js
    ports:
      - "3001:80"

  test-site:
    image: nginx:alpine
    container_name: merchant_test_site
    volumes:
      - ./frontend/test-site:/usr/share/nginx/html
    ports:
      - "8080:80"

  api:
    image: node:18-alpine
    container_name: payment_api
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install --no-audit --no-fund || true; node backend/src/server.js"
    environment:
      - DB_USER=gateway_user
      - DB_PASSWORD=gateway_pass
      - DB_NAME=payment_gateway
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    healthcheck:
      # Using wget as it is standard in alpine images
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/api/v1/test/jobs/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile.worker
    container_name: gateway_worker
    environment:
      - DB_USER=gateway_user
      - DB_PASSWORD=gateway_pass
      - DB_NAME=payment_gateway
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
      - WEBHOOK_RETRY_INTERVALS_TEST=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_healthy

  test-merchant:
    image: node:18-alpine
    container_name: test_merchant
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "node backend/src/test_merchant_webhook.js"
    ports:
      - "4000:4000"
    depends_on:
      api:
        condition: service_healthy

volumes:
  pgdata:
    driver: local